version: '2'
services:
  db:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    build: ./web
    image: web
    command: service nginx start
    ports:
      - "8080:80"
    depends_on:
      - app
  app:
    build: ./app
    image: app
    command: bash start
    volumes:
      - ./app:/app
    volumes_from:
      - box
    expose:
      - "3000"
    depends_on:
      - db
  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
